---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-sample-app
spec:
  selector:
    matchLabels:
      app: cicd-sample-app
  replicas: 1
  template:
    metadata:
      labels:
        app: cicd-sample-app
    spec:
      containers:
      - name: cicd-sample-app
        image: gcr.io/<PROJECT_ID>/cicd-sample-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-sample-app
spec:
  type: NodePort
  selector:
    app: cicd-sample-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
