name: Automated testing for pull request

on:
  pull_request:

env:
  PROJECT_ID: <PROJECT_ID>

jobs:
  pullreq_auto_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '272.0.0'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - run: gcloud builds submit . --config cloudbuild.yaml --project ${PROJECT_ID} --gcs-log-dir=gs://<BUCKET_NAME>/logs
